### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by yogaajie2** [yogaajie2/moviebook#1]
- [ ] Add storybook integration for the components
- [ ] Rating: fix 0 rating
- [ ] Now Playing: change year to genre
- [ ] Upcoming: change year to exact release date
